### ISSUE TITLE
Lines without children

### ISSUE THREAD

**Issue by edstratford** [oaregithub/oare_sql#13]
Gertrudius:   type.line which do not have any children:
SELECT * FROM text_epigraphy WHERE type = "line" AND uuid NOT IN (SELECT DISTINCT parent_uuid FROM text_epigraphy WHERE parent_uuid IS NOT NULL);

**Comment by edstratford** [comment]
There are 95 texts here. Very good catch - cannot explain yet , for example AKT 6c 528... the id numbers for the lines are all consecutive, so it seems the content int he lines never came into the SQL db... will take time to fix all of these.

**Comment by edstratford** [comment]
Have created google sheet to track progress on resolution of this issue:
https://docs.google.com/spreadsheets/d/1krBDXEI9bJ2ETaOxX9PjkPoPIB55FsvQgFpa_ziiztA/edit#gid=0

**Comment by Gertrudius** [comment]
I've gone through all of the entries in the sheet fixed all that I could. There are three remaining problem texts that have not been pulled out to a separate issue that you will probably need to look at yourself.

**Comment by edstratford** [comment]
Reviewed last three and addressed problems pertinent to this issue in each case.
