### ISSUE TITLE
`table`.`uuid` columns not currently included in `uuid`.`uuid`

### ISSUE THREAD

**Issue by Gertrudius** [oaregithub/oare_sql#25]
This effects:
`comments`.`uuid`
`errors`.`uuid`
`event`.`uuid`
`group_allowlist`.`uuid`
`group_edit_permissions`.`uuid`
`public_denylist`.`uuid`
`reset_password_links`.`uuid`
`text_drafts`.`uuid`
`threads`.`uuid`

Also, `unique_spellings`.`uuid` seems to be identical to the associated `dictionary_spelling`.`uuid` for the given spelling, and hence all of its associated `uuid`.`table_references` are for "dictionary_spelling". 
_____________________

My current philosophy is that those tables that are directly related to the data on the tablets, whether that's the words, grammar, signs, or persons mentioned etc. should be included in `uuid`.`uuid` to provide an extra layer of security to ensure the integrity of our data. Of the above tables, the only ones that should be included are possibly `event` and `unique_pellings` once a distinct uuid column is added for that table.

**Comment by edstratford** [comment]
unique spellings was just a place for me to try some logic. I don't think we need to add it to the uuid table (possible change in future) - as such, creating unique uuids for that table is not yet necessary.

a trigger for event should be added to the uuid table

I agree that all other tables need not be added to the uuid table.

**Comment by Gertrudius** [comment]
The necessary triggers have been added, and all missing `event`.`uuid` have been added to `uuid`.`uuid`. As such I'm closing the issue.
