### ISSUE TITLE
_before_ and _after_ nomenclature in the iterative stored procedures

### ISSUE THREAD

**Issue by Gertrudius** [oaregithub/oare_sql#27]
I'd like to change the "_before_" and "_after_" nomenclature in the iterative stored procedures to "inclusive" and "exclusive." Not only does this avoid any confusion with the "before" and "after" syntax of triggers, but it would also make it more explicit that they are either including or excluding the object on which it is called.

**Comment by edstratford** [comment]
Approve.

**Comment by Gertrudius** [comment]
Name changes have been implimneted.
