### ISSUE TITLE
lines in text_epigraphy whose children have a different line number

### ISSUE THREAD

**Issue by Gertrudius** [oaregithub/oare_sql#30]
SELECT te1.uuid,te2.uuid,te1.type,te2.type,te1.line,te2.line FROM text_epigraphy AS te1
INNER JOIN text_epigraphy AS te2
	ON te1.uuid = te2.parent_uuid AND te1.line != te2.line;

**Comment by edstratford** [comment]
All these instances have been fixed manually.
