### ISSUE TITLE
Hierarchy text objects that are missing from text, and text objects missing from hierarchy

### ISSUE THREAD

**Issue by Gertrudius** [oaregithub/oare_sql#31]
(posted by Harrison) Couple of data issues I’ve found:
The hierarchy row with UUID ebaa57fb-55f2-11eb-bf9e-024de1c1cc1d references a non-existent text.
There are 4 rows in text that don’t appear in the hierarchy.object_uuid column. Maybe I’m misunderstanding, but that seems like it would be incorrect.

**Comment by edstratford** [comment]
Through efforts from Gertrudius and Stratford, these issues have been resolved.
