### ISSUE TITLE
check for truncated uuid's

### ISSUE THREAD

**Issue by Gertrudius** [oaregithub/oare_sql#39]
as seen in issue #37, there are some uuids that are missing one or more characters. It would be useful to develop a stored procedure for checking for this issue using logic like:

SELECT * FROM text_discourse WHERE CHAR_LENGTH(parent_uuid) != 36;

**Comment by edstratford** [comment]
I checked the following tables finding no errors, adapting the query above for each table and relevant column:

text_epigraphy
text_discourse
text_markup
text_drafts
text
user
uuid
user_group
value
variable
tree
threads
spatial_unit
sign
sign_org
sign_reading
sign_sibling
resource
public_denylist
quarantine_text
person
period
link
hierarchy
field
event
dictionary_word
dictionary_form
dictionary_spelling
dictionary_spelling_epigraphy
comments
concept
bibliography
archive
asset
alias

I did find a few hits with:
SELECT * FROM item_properties WHERE CHAR_LENGTH(reference_uuid) != 36;
Fixed those - easy to REGEXp the shortened uuid in the uuid table.
(no other problems in item_properties)

**Comment by edstratford** [comment]
All known examples in important tables have been resolved. May be good to add this to the checks we want to develop.
