### ISSUE TITLE
Discourse units that do not resolve down to a number, word, or region

### ISSUE THREAD

**Issue by Gertrudius** [oaregithub/oare_sql#42]
Many of them have item_properties references, which may be why they weren't deleted along with the other childless discourse units, but these probably need to be removed for the various iterative value checkers/fixers to work correctly.
```
SELECT * FROM text_discourse
WHERE `type` NOT IN ('region','number','word')
AND uuid NOT IN (SELECT parent_uuid FROM text_discourse WHERE parent_uuid IS NOT NULL)
AND parent_uuid IS NOT NULL
-- AND uuid IN (SELECT reference_uuid FROM item_properties)
```

**Comment by edstratford** [comment]
I only see 5 left. Is that consistent with what you see?

**Comment by Gertrudius** [comment]
Yeah, five is consistent with what I am getting now, though I could have sworn I was getting like 130 when I first posted this issue. Maybe that was just on my local instance after running my script for issue #7, I'll have to double-check that, my bad.

**Comment by Gertrudius** [comment]
After checking over an older export and various fixes I've been working on, it looks like 5 is the correct number. I must have remembered 130 from something else.

**Comment by edstratford** [comment]
No problem! I fixed all five hits manually.
