### ISSUE TITLE
discrepency between count and max values in texts

### ISSUE THREAD

**Issue by Gertrudius** [oaregithub/oare_sql#44]
Here are some queries that note a discrepancy between the count of discourse or epigraphic units in a text, and the max obj_in_text/object_on_tablet_value:

SELECT * FROM 
(SELECT COUNT(text_uuid) AS this_count, text_uuid FROM text_epigraphy GROUP BY text_uuid) AS te1
INNER JOIN
(SELECT MAX(object_on_tablet) AS this_max, text_uuid FROM text_epigraphy GROUP BY text_uuid) AS te2
	ON te1.text_uuid = te2.text_uuid
	AND this_count != this_max;

SELECT * FROM 
(SELECT COUNT(text_uuid) AS this_count, text_uuid FROM text_discourse GROUP BY text_uuid) AS td1
INNER JOIN
(SELECT MAX(obj_in_text) AS this_max, text_uuid FROM text_discourse GROUP BY text_uuid) AS td2
	ON td1.text_uuid = td2.text_uuid
	AND this_count != this_max;

**Comment by oaregithub** [comment]
Two texts in text epigraphy (one with three line gap, other with epigraphicUnit starting at 2 instead of 1, both fixed.

Several texts in  text_discourse -- all fixed now.
