### ISSUE TITLE
`text_epigraphy`.`discourse_uuid` whose signs occur on lines removed by 2 or more lines

### ISSUE THREAD

**Issue by Gertrudius** [oaregithub/oare_sql#45]
SELECT te1.uuid, te2.uuid, te1.parent_uuid, te1.text_uuid, te1.char_on_tablet, te2.char_on_tablet, te1.line, te2.line, te1.discourse_uuid FROM text_epigraphy AS te1
INNER JOIN text_epigraphy AS te2
ON te1.discourse_uuid = te2.discourse_uuid
AND te1.line != te2.line
WHERE te1.discourse_uuid IS NOT NULL
AND te2.discourse_uuid IS NOT NULL
AND te1.line+1 < te2.line
ORDER BY te1.text_uuid, te1.object_on_tablet;

**Comment by edstratford** [comment]
Strange that these did not show up in the earlier search, but they are legitimate. Will take me a few days to manually fix.
