### ISSUE TITLE
unexpected NULL in `text_discourse.explicit spelling`

### ISSUE THREAD

**Issue by Gertrudius** [oaregithub/oare_sql#47]
I noticed that we have several discourse_units with a `type` of "word" or "number" that don't seem to have any `explicit_spelling` data. I ran the `update_discourse_spellings` procedure on them, and we still have 123 that might need to be looked at individually.

```
SELECT * FROM text_discourse 
WHERE `type` IN ('word','number')
AND (explicit_spelling IS NULL);
```

**Comment by edstratford** [comment]
There is only 1 left that I see and this is VS 26 125 (VAT 13505) (text_uuid = 66be9f2d-031e-7c33-c099-f46f4ca67b70) where line 13 is at the front of the obj_in_text sequence, possibly because line 13 had a char on tablet sequence problem (now fixed).

**Comment by Gertrudius** [comment]
The issue with VS 26 125 stemmed from the fact that the given 'sign' was actually the 'break' that begins the text, but it was erroneously placed, probably through a combination of having an incorrect type of "sign" from Ochre, compounded by the various ordering scripts I've used over the years to try and clean things up. I've fixed that issue along with some other numbering stuff caused by it.
