### ISSUE TITLE
texts that have order discrepencies between `side` and `object_on_tablet`

### ISSUE THREAD

**Issue by Gertrudius** [oaregithub/oare_sql#51]
The below texts were found by the script in #48 when checking if the `object_on_tablet values` line up when ordering by `side`. I've seen both situations where `side` values are incorrect and where the `object_on_tablet` values are wrong, so they will probably need to be fixed manually.

EDIT: I've gone through the list and resolved most of those that I could. The most prevalent problem was lo.e. and u.e. being flipped, but usually the object_on_tablet values were correct. This often corresponded to the publication not making a distinction between the two, so it may have happened when importing into ochre.

```BIN 6 197 | bf3fd270-8834-f6d0-37ff-0eb7c5f54a17 | upper edge appears first in "BIN 6_bag"
BIN 6 41 | 6b079cae-76ff-2850-9598-0219fc2b91f2 | BIN_6 pdf and BIN 6_bag suggest a 4 line break, though neither reflect that in their numbering, with the pdf simply continuing the numbering without increasing by four or doing it after the break.
CCT 1 11b (BM 113574a) | d4142f7c-9798-359f-df45-e15113bb7d7a | my sign reading isnt good enough to figure out whats going on, but it appears line 8 in the CCT 1 handcopy corresponds to line 12 in our text, so there are some extra lines coming from somwhere
CCT 6 45d (BM 113577a) | eaf139da-935e-40eb-b5c9-f87eba6f4abf | listed as on "O" although that seems unlikely
Chantre 13 | 25c06304-3f31-4f4d-9a78-71ea09be7218 | find translit
ICK 2 46 | ffc2eb0d-0c9b-4b75-9531-768a9760e86f | the ICK 2 pdf shows that this one seems to have the incorrect sides applied, I thing the lo.e. should be the rev., but I don't see where the rev. with line 6 is comming from
Kt 87/k 546 | 163988e4-2842-48e5-ae5d-8d5a6a154db9 | find translit
Kt 91/k 511 (AKT 8 243) | 9ea48b3f-9a81-4bf1-b6a9-67a9d786a475 | AKT 8 243 lists the side between obv. and rev. as "u.e.", but it includes a witness. is this just to avoid reprisenting breaks, or should it be an lo.e.?
Kt 92/k 502 (AKT 11a 130) | af9bb45b-41a8-476b-b7bf-b1809df781d1 | page 252 missing from AKT 11 pdf
Kt c/k 108+276 OVERLAP with 108? | da4615d3-7dd4-4363-bb9c-104e8673b917 | find translit
Kt c/k 192 | 9d32ac33-88ff-446a-8ed5-3270118ae4ea | find translit
Kt c/k 436 | 774cb670-fbab-4590-8700-a204480a9352 | there seems to be two obv., and their oot are out of order?
Kt c/k 643a | ee6d8573-61eb-4b22-ad08-ebc49742be16 | find translit
Kt c/k 846a | 9c391f82-6755-4922-bd63-a921e879329c | find translit
Kt m/k 48 | f6ed031a-4fba-4bfa-8c34-77c0e10c28d8 | side correct
Kt m/k 97 | b88eb0c5-c1aa-48aa-b253-af5f05117552 | find translit
TMH 1 15f | 9a6cdd25-c624-44e4-dbf1-00913b3b71a7 | u.e. preceeds obv. in pdf. not sure what to do with that```

**Comment by edstratford** [comment]
Responses:

CCT 1 11b - good thought - our database corrects the sides (obv.!) from what was represented in the handcopy. So it's fine.
CCT 6 45d - fixed
Chantre 13 - located translate and corrected side designation (interepreted to be u.e.)
87/k 546 corrected lo.e. to u.e. (located transit)
91/k 511 fixed
92/k 502 fixed
Kt c/k 108+276 fixed
c/k 192 fixed
c/k 436 fixed
c/k 643a fixed
c/k 846a fixed
m/k 48 fixed (line numbers too)
m/k 97 - checked transit - must have been an error in the edge - changed to u.e. fixed
TMH 1 15f --- this is effectively sloppy tablet writing, starting on the u.e. (or an editor that is too fastidious is determining where the u.e. ends and the obv. begins...  leaving this one here.

**Comment by edstratford** [comment]
*** BIN 6 41 -- yeah this is a problem -- still need to address our policy for the database on cases like this...

**Comment by edstratford** [comment]
Listed BIN 6 41 as separate issue.
