### ISSUE TITLE
Wrong tablet image with ICK 2 39?

### ISSUE THREAD

**Issue by Gertrudius** [oaregithub/oare_sql#52]
It looks like the image associated with ICK 2 39 does not match the transliteration

**Comment by edstratford** [comment]
I'm not getting an image for the tablet at all ...

![image](https://github.com/oaregithub/oare_sql/assets/29107053/b4d2a6f2-a1d5-417a-96f0-bb9b39559bfb)

**Comment by Gertrudius** [comment]
Thats odd, because I'm still getting this:
![image](https://github.com/oaregithub/oare_sql/assets/81266071/558a439a-81dc-4047-816e-6f048e9ed2a8)

**Comment by Gertrudius** [comment]
I tried clearing the cache for that text and the image seems to go away after that, as long as I access the text through the front end. If I paste the text_uuid into the address, the image seems to come back, regardless of what text I navigate from. I'm really not sure whats causing this, especially if it's not happening for you at all.

**Comment by edstratford** [comment]
Not reproduceable
