### ISSUE TITLE
Kt 94/k 287 missing all but one sign

### ISSUE THREAD

**Issue by Gertrudius** [oaregithub/oare_sql#54]
At this point, it might be easiest to delete this text and import it again, unless the front end edit feature is robust enough to handle it.

https://oare.byu.edu/epigraphies/56eed087-8e41-4676-bfea-034d078157ac

SELECT te.* FROM text_epigraphy AS te
WHERE text_uuid = "56eed087-8e41-4676-bfea-034d078157ac"
ORDER BY text_uuid, side, object_on_tablet

tranliteration from kt 94,279-359_bag reads:
kt 94/k 287
KIŠIB Dan-A-šùr DUMU Ir-n[u-id]
KIŠIB Dan-A-šùr DUMU A-zu-⌈x⌉
ša ší-bu-tí-šu-nu DUB-pu-um
ša IGI GÌR ša A-šùr
a-na a-wa-tim							5
a-ni-a-tim
kà-ru-um Dur4-⌈hu⌉-mì-⌈it⌉					rev.
i-dí-ni-a-tí-ma
DUB-pá-am IGI GÌR
ša A-šur ni-dí							10

**Comment by edstratford** [comment]
Was able to add missing lines and seal impressions via edit interface on front end.
