### ISSUE TITLE
a fair number of texts that are not loading on the front end

### ISSUE THREAD

**Issue by Gertrudius** [oaregithub/oare_sql#55]
most of them throw an error like this:

![image](https://github.com/oaregithub/oare_sql/assets/81266071/b965ec95-c912-4436-8783-f6d054cd8a32)

https://oare.byu.edu/epigraphies/42c5ae98-1faa-4ae1-81a6-ae05f6f62f93

**Comment by edstratford** [comment]
Figured out what this was. I had not properly updated the collection parent uuids in the hierarchy table - fixed.
