### ISSUE TITLE
Review sign_sibling table

### ISSUE THREAD

**Issue by oaregithub** [oaregithub/oare_sql#58]
The table is currently empty. Am preparing to add content. In testing, got error message for adding row:

Executing:
INSERT INTO `oarebyue_0.3`.`sign_sibling` (`uuid`, `sign_uuid`, `sibling_uuid`, `gestalt`, `leading`) VALUES (UUID(), '224e74d6-36e4-3215-e396-51d5f30cfc53', '30d93118-267f-c347-def3-58fd8738fecf', '2', '1');

Operation failed: There was an error while applying the SQL script to the database.
ERROR 1452: 1452: Cannot add or update a child row: a foreign key constraint fails (`oarebyue_0.3`.`sign_sibling`, CONSTRAINT `sign_sibling_ibfk_1` FOREIGN KEY (`uuid`) REFERENCES `uuid` (`uuid`) ON DELETE RESTRICT ON UPDATE RESTRICT)
SQL Statement:
INSERT INTO `oarebyue_0.3`.`sign_sibling` (`uuid`, `sign_uuid`, `sibling_uuid`, `gestalt`, `leading`) VALUES (UUID(), '224e74d6-36e4-3215-e396-51d5f30cfc53', '30d93118-267f-c347-def3-58fd8738fecf', '2', '1')

The offending uuid exists in the uuid table with appropriate table reference - review FK constraints on table.

**Comment by Gertrudius** [comment]
It looks like we don't have trigger support for this table yet. I'll go ahead and add the needed triggers.

**Comment by Gertrudius** [comment]
Triggers were added and the above insert went through. I'm calling this fixed.
