### ISSUE TITLE
duplicates in `value`.`name`

### ISSUE THREAD

**Issue by Gertrudius** [oaregithub/oare_sql#75]
It looks like we have a number of possibly duplicate entries in the `value` table. 

```SELECT * FROM value WHERE `name` IN (SELECT `name` FROM value GROUP BY `name` HAVING COUNT(`name`) > 1) ORDER BY `name`;```

For the most part these don't concern me too much, but the ones below impact a procedure I'm writing, so if @edstratford could let me know if we need to retain both in these particular cases that would be great.

```
127d2dd1-b8ef-11ec-bcc3-0282f921eac9	II/aleph	
127d31ad-b8ef-11ec-bcc3-0282f921eac9	II/aleph	
95d08d84-9947-44fa-b009-65d35700112f	PuRuSt	PuRuSt
3dea8820-491d-41f3-91ab-ab4670c1addc	PuRuSt	PuRuSt
ec55b2c7-4af2-9655-871f-b6414e128f41	b	
89bdc026-72f6-8c42-453c-b7a9ba4fcf3c	b	
85336bdb-adf6-c198-2c0d-55fdc0630405	k	
67c95d1c-3b57-5161-684a-3efc76352041	k	
a1b7dc75-d35a-75a1-e492-341c3556fe76	p	
fc7d0695-f8b1-4bdb-e6a9-7ac87ba5f80b	p	
4b8fad39-5e98-29fe-1a43-ffdfb097d5d6	q	
b44d5c47-a25b-7052-f184-ce9520d04ad6	q	
fff2bfe8-ab55-964d-c07d-2b056fa60239	u	
4273f76a-73a5-3d8b-4616-6e4376c685ba	u	
78a6d5a1-69b9-19ae-c891-1ef63f53a6bd	z	
cf807e9f-1434-e29e-5bb3-c0cc0687c6c6	z	
d734471d-2afa-d90e-ee42-efdc7b418018	š	
2f71281f-8b9d-ac89-ad47-cc6f9e91a53a	š	
b9888c07-5777-29c4-8c22-edf32e61be2e	ṣ	ṣ
29bd5a95-67c9-2cc9-a4f3-2f2b9b677eff	ṣ	
cf56f5ba-0a8c-8994-8546-d21308e016a5	ṭ	
a140385d-f3df-0b4d-2df7-ff7d6a573816	ṭ	
d1176413-6836-421f-8013-46ab28d4726d	ṯ	
c0ad1e0c-7c75-c419-6cc4-51485ca2fd88	ṯ	
		
```

**Comment by edstratford** [comment]
All but II/aleph and PuRust have been corrected by naming the one 'Proto-Semitic b' etc. 

The other two (II/aleph and PuRuSt) were genuine duplicates. After determining that neither of each appeared in item_properties, one of each was removed from hierarchy, value, and uuid tables. 

Will review other duplicates as well.
